### PR TITLE
Fix can't reply message and reply message now can be used

### PR DESCRIPTION
**Pull request by aancw**
I'm trying to fix this issue https://github.com/arcestiaishere/klasemate/issues/8 . I will fix forward message feature later.

### CODE REVIEW

**Comment by aancw** [comment]
I'm forgot about the subject of message. it will show like this if nested reply : Re:Re:Ini Subject

**Comment by arcestia** [comment]
Thanks

**Comment by aancw** [comment]
Just remove "Re:". from SendReply function and i will fix this when forward feature already done

**Comment by aancw** [comment]
Just remove "Re:". from SendReply function and i will fix this when forward feature already done

**Pull request merged**
